[tool.poetry]
name = "checkov"
version = "0.1.0"
description = ""
authors = ["Adam Varsano <avarsano@paloaltonetworks.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^7.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
