remote_theme: bridgecrewio/checkov-theme

site_author: Bridgecrew
repo_url: "https://github.com/bridgecrewio/checkov/"

edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: false
hljs_style: github-gist
tipue_search:
  include:
    pages: true
  exclude:
    files: [search.html]
