name: pipenv-update
on:
  schedule:
    - cron:  '8 22 * * 1'
  workflow_dispatch:

jobs:
  pipenv-update:
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: dschep/install-pipenv-action@v1
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          pipenv update
          git add -u
          git commit -m "update pipenv packages"
        env:
          GITHUB_TOKEN: ${{ github.PAT_TOKEN }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          title: '[AUTO-PR] Update pipenv packages'
          body: |
            bump pipenv packages
            - Auto-generated by [pipenv-update github action](https://github.com/bridgecrewio/checkov/blob/master/.github/workflows/pipenv-update.yml)
          labels: automated pr
          branch: pipenvfix
          branch-suffix: timestamp
