name: pipenv-update
on:
  schedule:
    - cron:  '8 22 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pipenv-update:
    runs-on: [self-hosted, public, linux, x64]
    permissions:
      contents: write
      pull-requests: write
    env:
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT_SECRET }}
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4  # v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f  # v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install pipenv
        run: |
          python -m pip install --no-cache-dir --upgrade pipenv
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          pipenv update
          git add -u
          git commit -m "update pipenv packages"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c  # v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          title: '[AUTO-PR] Update pipenv packages'
          body: |
            bump pipenv packages
            - Auto-generated by [pipenv-update github action](https://github.com/bridgecrewio/checkov/blob/main/.github/workflows/pipenv-update.yml)
          labels: automated pr
          branch: pipenvfix
          branch-suffix: timestamp
